name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Build Docker image
      run: |
        docker build -t smartlocalaichatbot:latest .

    - name: Push Docker image to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image
      run: |
        docker tag smartlocalaichatbot:latest ${{ secrets.DOCKER_USERNAME }}/smartlocalaichatbot:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/smartlocalaichatbot:latest

    - name: Deploy to server
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
          docker pull ${{ secrets.DOCKER_USERNAME }}/smartlocalaichatbot:latest
          docker stop smartlocalaichatbot || true
          docker rm smartlocalaichatbot || true
          docker run -d -p 5000:5000 --name smartlocalaichatbot ${{ secrets.DOCKER_USERNAME }}/smartlocalaichatbot:latest
        EOF
